function Garbor_filter=computeChange(x,y,theta,r)%theta表示方向，r表示纵横比
%b=1;%表示带宽
%lamda=3;%表示波长
%faye=pi/4;%表示相位角
Wt=30;%Gabor的小波时域窗口
x1=x*cos(theta)+y*sin(theta);
y1=-x*sin(theta)+y*cos(theta);
deta=Wt/sqrt(2);%deta是高斯函数沿两个坐标轴的标准差
%deta=lamda/pi*sqrt(log(2)/2)*((2^b+1)/(2^b-1));
%Garbor_filter=exp(-(x1^2/2*deta^2)-(r^2*y1^2)/2*deta^2)*exp(1i*(2*pi*x1/lamda+faye));
Garbor_filter=(1/(2*pi*deta^2))*exp(-(x1^2+y1^2)/(2*deta^2))*(exp(1j*r*x1)-exp(-r^2*deta^2/2));
